### ISSUE TITLE
Unable to Add Contracts from Repository 

### ISSUE THREAD

**Issue by ChatContractAI** [chatcontract/public-issues#308] opened 2024-06-30 17:52 UTC
Unable to Add Contracts from Repository.

Desc: When i add contracts from repository, i get error on screen with a Try Again button. On clicking the Try Again Button the Error appears again. The error popup window does not allows the user to access the "Submit Feedback Option" User needs to first close the error popup and after that user can access the submit feedback option which also causes a friction for user to report the bug.

Steps to Replicate:
Go to Repository Page >> Click on Button for Add Contracts >> Select the Contracts for upload >> Proceed to Upload >> Verify the selected Files >> Proceed Button >> Error Popup Appears.

  Description - [What went wrong? Keep it brief.]
  Steps to Reproduce - [How can we make this bug happen?]
  Expected Behavior - [What did you expect to see?]
  Actual Behavior - [What did you actually see?]
  Error - {"stack":"SyntaxError: Unexpected token '<', \"<!DOCTYPE \"... is not valid JSON","message":"Unexpected token '<', \"<!DOCTYPE \"... is not valid JSON"}
   
      UserId - a835a711-7301-4d4b-81f3-1b10da74efb0 
      Detailed Message - {"stack":"SyntaxError: Unexpected token '<', \"<!DOCTYPE \"... is not valid JSON","message":"Unexpected token '<', \"<!DOCTYPE \"... is not valid JSON"}

**Comment by Mayank-dev1822** [comment] 2024-07-02 11:23
This bug is a duplicate of: https://github.com/chatcontract/public-issues/issues/309

**Closed as completed** 2024-07-04 11:03 UTC
Labels: bug, Backend
